name: Bug Report
description: Open a new bug report
title: "[BUG]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug.

  - type: textarea
    id: bug-description
    attributes:
      label: Description
      description: Briefly describe the bug. Please be as specific as possible.
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please describe the environment in which the program was run. What operating system are you using? What version of Python are you using? How did you install python-bugger?
  - type: textarea
    id: Execution
    attributes:
      label: Execution
      description: How did you run the program? Please give the exact command you used, such as `py-bugger -e ModuleNotFoundError`.
  - type: textarea
    id: target-project
    attributes:
      label: Target project
      description: What project did you run py-bugger against? If it's a public project, please provide a link to the project.
  - type: textarea
    id: results
    attributes:
      label: Results
      description: What were the results of running py-bugger against the target project? Did it fail to introduce the requested exception type? Did py-bugger crash? (If so, please provide the full traceback.)
  - type: textarea
    id: insights
    attributes:
      label: Insights
      description: Do you have any insights into what might have caused this bug? Is there anything else you can share that might be helpful in identifying the root cause, and developing a fix?
